version: "3.9"

services:

  db:
    image: mariadb:latest
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass123
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sensor_db
    ports:
      - "63306:3306"

  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8100:8000"
    depends_on:
      - db
