version: "3.9"

services:

  db:
    # image: mariadb:latest
    # restart: on-failure
    # volumes:
    #   - ./data/db:/var/lib/mariadb/data
    # environment:
    #   - MARIADB_DATABASE=sensor_db
    #   - MARIADB_USER=admin
    #   - MARIADB_PASSWORD=pass123
    #   - MARIADB_ROOT_PASSWORD=root

    image: mariadb
    environment:
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql

  web:

    image: app:django
    container_name: django_container
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # environment:
    #   - MARIADB_DATABASE=sensor_db
    #   - MARIADB_USER=root
    #   - MARIADB_PASSWORD=root
    depends_on:
      - db
