# Generated by Django 4.0.4 on 2022-09-15 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_status', models.IntegerField(choices=[(0, 'created'), (1, 'send'), (2, 'execution success'), (3, 'execution failed')], max_length=1)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('ip_addr', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw', models.CharField(max_length=255)),
                ('permission', models.IntegerField(choices=[(0, 'admin'), (1, 'user')], max_length=1)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcv_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.user'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.IntegerField(choices=[(0, 'Command log'), (1, 'Sensor_data log')], max_length=1)),
                ('logging_type', models.IntegerField(choices=[(0, 'request'), (1, 'response'), (2, 'receive')], max_length=1)),
                ('logging_msg', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.command')),
                ('sensor_data_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor_data')),
                ('sensor_uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Cow_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
                ('cow_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.cow')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='cow',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.farm'),
        ),
        migrations.AddField(
            model_name='command',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor'),
        ),
    ]
