# Generated by Django 4.0.4 on 2022-09-16 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.IntegerField()),
                ('command', models.IntegerField()),
                ('trigerring_period', models.IntegerField()),
                ('active_time', models.IntegerField()),
                ('period_time', models.IntegerField()),
                ('bit7', models.BooleanField()),
                ('bit6', models.BooleanField()),
                ('bit5', models.BooleanField()),
                ('bit4', models.BooleanField()),
                ('bit3', models.BooleanField()),
                ('bit2', models.BooleanField()),
                ('bit1', models.BooleanField()),
                ('bit0', models.BooleanField()),
                ('data_sending_period', models.IntegerField()),
                ('command_status', models.IntegerField(choices=[(0, 'created'), (1, 'send'), (2, 'execution success'), (3, 'execution failed')])),
                ('rcv_code', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('ip_addr', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('pw', models.CharField(max_length=255)),
                ('permission', models.IntegerField(choices=[(0, 'admin'), (1, 'user')])),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.CharField(max_length=255)),
                ('Acc_X', models.IntegerField()),
                ('Acc_Y', models.IntegerField()),
                ('Acc_Z', models.IntegerField()),
                ('Gyro_X', models.IntegerField()),
                ('Gyro_Y', models.IntegerField()),
                ('Gyro_Z', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('battery', models.FloatField()),
                ('rcv_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor')),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.user'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.IntegerField(choices=[(0, 'Command log'), (1, 'Sensor_data log')])),
                ('logging_type', models.IntegerField(choices=[(0, 'request'), (1, 'response'), (2, 'receive')])),
                ('response_code', models.IntegerField()),
                ('logging_msg', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.command')),
                ('sensor_data_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor_data')),
                ('sensor_uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cow_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=b'I00\n')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(auto_now=True)),
                ('cow_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.cow')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='cow',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.farm'),
        ),
        migrations.AddField(
            model_name='command',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sensor.sensor'),
        ),
    ]
