# Generated by Django 4.0.4 on 2022-09-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensor_data',
            table=None,
        ),
    ]
