# Generated by Django 4.0.4 on 2022-09-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_alter_sensor_data_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='port',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
