# Generated by Django 4.0.4 on 2022-11-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensor_port_alter_farm_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
