# Generated by Django 4.0.4 on 2022-11-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_user_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hash',
        ),
    ]
