# Generated by Django 4.0.4 on 2022-11-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_remove_user_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
